### ISSUE TITLE
Unhandled expection

### ISSUE THREAD

**Issue by chang3d** [Inspirare-LLC/Radzen.Blazor.GridExportOptions#2]
There is an unhandled exception when the buttons are clicked.

![image](https://user-images.githubusercontent.com/7635111/148293233-cc9068c8-7444-4687-9779-fa6639b35978.png)

**Comment by JonasPetraska** [comment]
Hi,

Do you have jquery included in your project?

**Comment by frankleib** [comment]
use the ald with <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" type="text/javascript"></script> and you will solve the problem ;)

**Comment by JonasPetraska** [comment]
Closing the issue, since the solution has been provided. Please open if the issue persists.
